### PR TITLE
Added Sign Up/Reset password buttons

### PR DESCRIPTION
**Pull request by RoyalSix**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1)

### CODE REVIEW

**Comment by klappy** [comment]
___
*[package-lock.json, line 0 at r1](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrAh9AhEhNxiS0Pcr6o:-LrAh9AhEhNxiS0Pcr6p:b-jncrom) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/ab68bf13a653360fd07d4accb6504296ae76a2c3/package-lock.json#L0)):*
I'd like us to switch over to using just `yarn` and not `npm` for package management. Can you remove this file from the PR?

**Comment by klappy** [comment]
___
*[src/components/authentication/LoginForm.js, line 91 at r1](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrAj0Jp0GqA1As2z3jA:-LrAj0Jp0GqA1As2z3jB:b5pbcit) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/ab68bf13a653360fd07d4accb6504296ae76a2c3/src/components/authentication/LoginForm.js#L91)):*
> ```JavaScript
> LoginFormComponent.propTypes = {
>   /** Configuration to use for sign up/forgot password flow */
>   config: PropTypes.object.isRequired,
> ```

Can we make this optional? If it is supplied then we can render the new footer.

**Comment by klappy** [comment]
___
*[src/components/authentication/LoginForm.js, line 66 at r1](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrAjF9XBUjYl-xaQWb9:-LrAjF9XBUjYl-xaQWbA:bpli3dc) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/ab68bf13a653360fd07d4accb6504296ae76a2c3/src/components/authentication/LoginForm.js#L66)):*
> ```JavaScript
>           }
>         />
>         <div className={classes.footer}>
> ```

Can you abstract this to outside of the return block?
Then you can wrap it with a conditional looking for config.server...
```js
let footer = <></>;
if (config &&  config.server) {
  footer = (
    <div className={classes.footer}>
      ...
    </div>
  );
}
```

Then in this place here: `{footer}`.

**Comment by klappy** [comment]
Looking good! I left some comments for LoginForm.

**Comment by klappy** [comment]
___
*[src/components/authentication/LoginForm.js, line 83 at r1](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrAq2Qk9vDwSuZqNfAj:-LrAq2Qk9vDwSuZqNfAk:b-wxetst) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/ab68bf13a653360fd07d4accb6504296ae76a2c3/src/components/authentication/LoginForm.js#L83)):*
> ```JavaScript
>         >
>           {(user) ? 'Logout' : actionText}
>         </Button>
> ```

Let's move the footer underneath the submit button and see how that looks.

**Comment by klappy** [comment]
___
*[src/components/authentication/LoginForm.js, line 72 at r1](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrArNuO1fmcEEVEr4wE:-LrArNuO1fmcEEVEr4wF:b-d1jdw1) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/ab68bf13a653360fd07d4accb6504296ae76a2c3/src/components/authentication/LoginForm.js#L72)):*
> ```JavaScript
>           </div>
>           <div className={classes.footer}>
>             <Typography color="primary" variant="caption" component="a" target="_blank" href={`${config.server}/user/forgot_password`}>Reset password</Typography>
> ```

Since the user typically forgets their password, we could just leave the text, `Forgot Password`.

**Comment by klappy** [comment]
___
*[src/components/authentication/LoginForm.js, line 69 at r1](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrAra2CC381Lc-OBuFX:-LrAra2CC381Lc-OBuFY:b-kdani) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/ab68bf13a653360fd07d4accb6504296ae76a2c3/src/components/authentication/LoginForm.js#L69)):*
> ```JavaScript
>           <div className={classes.footer}>
>             <Typography variant="caption">Don&apos;t have an account?&nbsp;</Typography>
>             <Typography color="primary" variant="caption" component="a" target="_blank" href={`${config.server}/user/sign_up`}>Sign Up</Typography>
> ```

We should probably ask about the final text for this but the DCS/Gitea site uses the wording, `Register`.

**Comment by klappy** [comment]
___
*[src/components/authentication/LoginForm.js, line 68 at r1](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrAsRsh8VUJWQzVCpNd:-LrAsRsh8VUJWQzVCpNe:b-rn5v74) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/ab68bf13a653360fd07d4accb6504296ae76a2c3/src/components/authentication/LoginForm.js#L68)):*
> ```JavaScript
>         <div className={classes.footer}>
>           <div className={classes.footer}>
>             <Typography variant="caption">Don&apos;t have an account?&nbsp;</Typography>
> ```

On this link: https://git.door43.org/user/login
It uses, `Need an Account?`

**Comment by RoyalSix** [comment]
Great suggested changes, just pushed.
I am using the same verbiage as `https://git.door43.org/` for consistency

**Comment by klappy** [comment]
___
*[src/components/authentication/LoginForm.js, line 36 at r2](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrEfzkD-XsftYuwTtDI:-LrEfzkE1zuuq-hhrgu0:b-p0p38e) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/3e68a0ac63bc2952e34f364711315ab6a567041c/src/components/authentication/LoginForm.js#L36)):*
> ```JavaScript
>     setFormData(_formData);
>   };
>   const {root, avatar, form, footer, submit} = classes;
> ```

I've explored doing this in the past but it doesn't seem to scale well. 
Naming conventions start to clash as we use the same names for components and data already, adding the same names in the namespace, makes it confusing what the variable actually holds.

**Comment by klappy** [comment]
___
*[src/components/authentication/LoginForm.js, line 78 at r2](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrEgd_lDdZrzJmaPYoE:-LrEgd_lDdZrzJmaPYoF:b1uh7n3) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/3e68a0ac63bc2952e34f364711315ab6a567041c/src/components/authentication/LoginForm.js#L78)):*
> ```JavaScript
>         {
>           config && config.server ? (
>             <>
> ```

The React Fragment (<></>) isn't needed here as the <div> is a valid singular element.

**Comment by klappy** [comment]
___
*[src/components/authentication/LoginForm.js, line 89 at r2](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrEgrGg0OVwHk5N5VLy:-LrEgrGg0OVwHk5N5VLz:brdayje) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/3e68a0ac63bc2952e34f364711315ab6a567041c/src/components/authentication/LoginForm.js#L89)):*
> ```JavaScript
>               </div>
>             </>
>           ) : null
> ```

This is typically where the <></> would go in place of the null. Technically not required here but seems a good practice as a React Element is always returned.

**Comment by klappy** [comment]
___
*[src/components/authentication/LoginForm.js, line 132 at r2](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrEhWu39YmgO9MGxfjM:-LrEhWu39YmgO9MGxfjN:b-8kmfou) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/3e68a0ac63bc2952e34f364711315ab6a567041c/src/components/authentication/LoginForm.js#L132)):*
> ```JavaScript
>   },
>   submit: {
>     marginBottom: theme.spacing.unit * 3,
> ```

We can take the bottom margin spacing down to `theme.spacing.unit * 2`.

**Comment by klappy** [comment]
___
*[src/components/authentication/LoginForm.js, line 98 at r2](https://reviewable.io/reviews/unfoldingword-box3/gitea-react-toolkit/1#-LrEk3IR73Jzbf9zFRx8:-LrEk3IR73Jzbf9zFRx9:b4p3dto) ([raw file](https://github.com/unfoldingword-box3/gitea-react-toolkit/blob/3e68a0ac63bc2952e34f364711315ab6a567041c/src/components/authentication/LoginForm.js#L98)):*
> ```JavaScript
> LoginFormComponent.propTypes = {
>   /** Configuration to use for sign up/forgot password flow */
>   config: PropTypes.object,
> ```

To help the auto doc gen spell out what is expected you can make the server string required if config is provided.
```js
config: PropTypes.shape({
  server: PropTypes.string.isRequired,
}),
```

**Pull request merged**
